services:
  streamlit:
    build:
      context: ./streamlit
    restart: unless-stopped
    expose:
      - 8501
    networks:
      - local
    depends_on:
      - postgres
      - mongodb
      - redis
  postgres:
    image: postgres:latest
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=pf9K6bCTkz2rgCzgN2AsWLRuK8
      - POSTGRES_DB=example
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=n2mYJ9BhU2AaVnrNZVzNJt4hsC
      - MONGO_INITDB_DATABASE=example
    networks:
      - local
  redis:
    image: redis:latest
    restart: unless-stopped
    expose:
     - 6379
    volumes:
      - redis-data:/data
    networks:
      - local
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - local
      - web
    depends_on:
      - streamlit
      - voila
      - dash
      - fastapi

networks:
  web:
    external: false
  local:
    external: false
    driver: bridge

volumes:
  postgres-data:
  mongodb-data:
  redis-data:
  caddy-data:
  caddy-config:
