services:
  alpinejs:
    build:
      context: services/alpinejs
    restart: unless-stopped
    volumes:
      - alpinejs-app:/app
    networks:
      - local
  pocketbase:
    build:
      context: services/pocketbase
    restart: unless-stopped
    expose:
      - 8008
    ports:
      - 8008
    volumes:
      - pocketbase-data:/pb/pb_data
    networks:
      - local
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
      - alpinejs-app:/app
    networks:
      - local
      - web
    depends_on:
      - alpinejs
      - pocketbase

networks:
  web:
    external: false
  local:
    external: false
    driver: bridge

volumes:
  caddy-data:
  caddy-config:
  pocketbase-data:
  alpinejs-app:
