services:
  fastapi:
    build:
      context: services/fastapi
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - local
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pf9K6bCTkz2rgCzgN2AsWLRuK8
      - POSTGRES_DB=example
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - local
      - web
    depends_on:
      - fastapi

networks:
  web:
    external: false
  local:
    external: false
    driver: bridge

volumes:
  postgres-data:
  caddy-data:
  caddy-config:
