version: "3.9"

services:  # remove all unused services
  streamlit:
    build:
      context: ./streamlit
    restart: unless-stopped
    expose:
      - 8501
    networks:
      - local
  voila:
    build:
      context: ./voila
    restart: unless-stopped
    expose:
      - 8866
    networks:
      - local
  dash:
    build:
      context: ./dash
    restart: unless-stopped
    expose:
      - 8050
    networks:
      - local
  fastapi:
    build:
      context: ./fastapi
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - local
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - local
      - web
    depends_on:  # remove all unused dependencies
      - streamlit
      - voila
      - dash
      - fastapi

networks:
  web:
    external: true
  local:
    external: false
    driver: bridge
