version: "3.9"

services:
  streamlit:
    build:
      context: ./streamlit
    restart: unless-stopped
    expose:
      - 8501
    networks:
      - local
  voila:
    build:
      context: ./voila
    restart: unless-stopped
    expose:
      - 8866
    networks:
      - local
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - local
      - web
    depends_on:
      - streamlit
      - voila

networks:
  web:
    external: true
  local:
    external: false
    driver: bridge
