services:
  frontend:
    image: "node:18.16.1-bullseye-slim"
    command: sleep infinity
    restart: unless-stopped
    volumes:
      - ../../:/workspaces:cached
    expose:
      - 5173

  backend:
    build:
      context: ../services/fastapi
    command: poetry run uvicorn backend.main:app --host 0.0.0.0 --port 8080 --reload
    restart: unless-stopped
    volumes:
      - ../services/fastapi/backend:/app/backend
    expose:
      - 8080
