site_name: Service Templates
docs_dir: content
site_dir: build
repo_url: https://git.point-8.de/ccauet/service-templates
repo_name: ccauet/service-templates
theme:
  name: material
  features:
    - instant
  palette:
    primary: blue
    accent: orange
  font:
    text: Fira Sans
    code: Fira Mono
markdown_extensions:
  - smarty
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - search
